<?php
$pageTitle = 'Site Map';
$pageDescription = 'A directory of every page in this site';
include ('includes/header.html')
?>

				<a href="amarettosour.php">Amaretto Sour</a><br />
				<a href="americano.php">Americano</a><br />
				<a href="angelface.php">Angel Face</a><br />
				<a href="aperolspritz.php">Aperol Spritz</a><br />
				<a href="applemojito.php">Apple Mojito</a><br />
				<a href="appletini.php">Appletini</a><br />
				<a href="aviation.php">Aviation</a><br />
				<a href="b52.php">B52</a><br />
				<a href="babyguinness.php">Baby Guinness</a><br />
				<a href="bacardi.php">Bacardi</a><br />
				<a href="bellini.php">Bellini</a><br />
				<a href="berrycaipiroska.php">Berry Caipiroska</a><br />
				<a href="betweenthesheets.php">Between The Sheets</a><br />
				<a href="blackrussian.php">Black Russian</a><br />
				<a href="bloodymary.php">Bloody Mary</a><br />
				<a href="bluehawaii.php">Blue Hawaii</a><br />
				<a href="bramble.php">Bramble</a><br />
				<a href="brandyalexander.php">Brandy Alexander</a><br />
				<a href="brandysour.php">Brandy Sour</a><br />
				<a href="caipiroska.php">Caipiroska</a><br />
				<a href="caipirinha.php">Caipirinha</a><br />
				<a href="casino.php">Casino</a><br />
				<a href="champagnecocktail.php">Champagne Cocktail</a><br />
				<a href="cloverclub.php">Clover Club</a><br />
				<a href="cosmopolitan.php">Cosmopolitan</a><br />
				<a href="cubalibre.php">Cuba Libre</a><br />
				<a href="daiquiri.php">Daiquiri</a><br />
				<a href="darkandstormy.php">Dark And Stormy</a><br />
				<a href="englishmojito.php">English Mojito</a><br />
				<a href="espressomartini.php">Espresso Martini</a><br />
				<a href="flatliner.php">Flatliner</a><br />
				<a href="french75.php">French 75</a><br />
				<a href="frenchconnection.php">French Connection</a><br />
				<a href="frenchmartini.php">French Martini</a><br />
				<a href="frozendaiquiri.php">Frozen Daiquiri</a><br />
				<a href="frozenmargarita.php">Frozen Margarita</a><br />
				<a href="gimlet.php">Gimlet</a><br />
				<a href="ginderby.php">Gin Derby</a><br />
				<a href="ginmartini.php">Gin Martini</a><br />
				<a href="ginsour.php">Gin Sour</a><br />
				<a href="godfather.php">Godfather</a><br />
				<a href="godmother.php">Godmother</a><br />
				<a href="harveywallbanger.php">Harvey Wallbanger</a><br />
				<a href="hemmingwayspecial.php">Hemmingway Special</a><br />
				<a href="horsesneck.php">Horse's Neck</a><br />
				<a href="hurricane.php">Hurricane</a><br />
				<a href="jagerbomb.php">Jagerbomb</a><br />
				<a href="japaneseslipper.php">Japanese Slipper</a><br />
				<a href="kamikaze.php">Kamikaze</a><br />
				<a href="keywestcooler.php">Key West Cooler</a><br />
				<a href="kir.php">Kir</a><br />
				<a href="kirroyal.php">Kir Royal</a><br />
				<a href="lemondropmartini.php">Lemon Drop Martini</a><br />
				<a href="lemondropshot.php">Lemon Drop Shot</a><br />
				<a href="longbeachicedtea.php">Long Beach Iced Tea</a><br />
				<a href="longislandicedtea.php">Long Island Iced Tea</a><br />
				<a href="lycheemojito.php">Lychee Mojito</a><br />
				<a href="lynchbourglemonade.php">Lynchbourg Lemonade</a><br />
				<a href="maitai.php">Mai Tai</a><br />
				<a href="manhatten.php">Manhatten</a><br />
				<a href="margarita.php">Margarita</a><br />
				<a href="mimosa.php">Mimosa</a><br />
				<a href="mintjulep.php">Mint Julep</a><br />
				<a href="mojito.php">Mojito</a><br />
				<a href="mojitoroyal.php">Mojito Royal</a><br />
				<a href="monkeygland.php">Monkey Gland</a><br />
				<a href="moscowmule.php">Moscow Mule</a><br />
				<a href="negroni.php">Negroni</a><br />
				<a href="oldfashioned.php">Old Fashioned</a><br />
				<a href="paradise.php">Paradise</a><br />
				<a href="pinacolada.php">Pina Colada</a><br />
				<a href="pinklady.php">Pink Lady</a><br />
				<a href="piscosour.php">Pisco Sour</a><br />
				<a href="planterspunch.php">Planters Punch</a><br />
				<a href="pornstarmartini.php">Pornstar Martini</a><br />
				<a href="portoflip.php">Porto Flip</a><br />
				<a href="ramosfizz.php">Ramos Fizz</a><br />
				<a href="robroy.php">Rob Roy</a><br />
				<a href="rumfashioned.php">Rum Fashioned</a><br />
				<a href="russianspringpunch.php">Russian Spring Punch</a><br />
				<a href="rustynail.php">Rusty Nail</a><br />
				<a href="sazerac.php">Sazerac</a><br />
				<a href="screwdriver.php">Screwdriver</a><br />
				<a href="seabreeze.php">Sea Breeze</a><br />
				<a href="sexonthebeach.php">Sex On The Beach</a><br />
				<a href="shirleytemple.php">Shirley Temple</a><br />
				<a href="shittynipple.php">Shitty Nipple</a><br />
				<a href="sidecar.php">Sidecar</a><br />
				<a href="singaporesling.php">Singapore Sling</a><br />
				<a href="slipperynipple.php">Slippery Nipple</a><br />
				<a href="stinger.php">Stinger</a><br />
				<a href="summerpimms.php">Summer Pimms</a><br />
				<a href="tequilasunrise.php">Tequila Sunrise</a><br />
				<a href="tgv.php">TGV</a><br />
				<a href="tomcollins.php">Tom Collins</a><br />				
				<a href="tommysmargarita.php">Tommy's Margarita</a><br />
				<a href="tuxedo.php">Tuxedo</a><br />
				<a href="vespermartini.php">Vesper Martini</a><br />
				<a href="virginmary.php">Virgin Mary</a><br />
				<a href="virginmojito.php">Virgin Mojito</a><br />
				<a href="virginpinacolada.php">Virgin Pina Colada</a><br />
				<a href="vodkagimlet.php">Vodka Gimlet</a><br />
				<a href="vodkamartini.php">Vodka Martini</a><br />
				<a href="whiskeysour.php">Whiskey Sour</a><br />
				<a href="whitelady.php">White Lady</a><br />
				<a href="whiterussian.php">White Russian</a><br />
				<a href="woowoo.php">Woo Woo</a><br />
				<a href="yellowbird.php">Yellow Bird</a><br />
				<a href="zombie.php">Zombie</a><br />
				


<?php
include ('includes/footer.html')
?>